### ISSUE TITLE
Admin list post integration

### ISSUE THREAD

**Issue by amirmsoltani** [amirmsoltani/denanova#7]

**Comment by amirasahraee** [comment]
The sent pagination values are not correct.

**Comment by amirmsoltani** [comment]
> The sent pagination values are not correct.

@amirasahraee  I don't understand what you mean. could you explain more with picture about this problem?

**Comment by amirasahraee** [comment]
@amirmsoltani The number of files will be sent!

![Screenshot from 2022-08-30 17-13-47](https://user-images.githubusercontent.com/87465114/187440104-6ac77f27-a42b-4ebe-92a3-db1cfcc47443.png)

**Comment by amirmsoltani** [comment]
> @amirmsoltani The number of files will be sent!
> 
> ![Screenshot from 2022-08-30 17-13-47](https://user-images.githubusercontent.com/87465114/187440104-6ac77f27-a42b-4ebe-92a3-db1cfcc47443.png)

Right.
you can replace files => post in files [companies](https://github.com/amirmsoltani/denanova/blob/develop/pages/admin/companies.tsx) and [products](https://github.com/amirmsoltani/denanova/blob/develop/pages/admin/products.tsx) at line 24
